name = "SpectrogramRecipes"
uuid = "5356d540-183f-4115-83e0-e870f9a629b6"
authors = ["David MacMahon <davidm@astro.berkeley.edu> and contributors"]
version = "0.1.0"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
RecipesBase = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
